/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pokerbot;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Julio
 */
public class PlayerStatus extends javax.swing.JPanel {
    private Game _parent;
    private String Name;
    private boolean visible;
    public void parent(Game g){
        _parent = g;
    }
    public JTextField getJtDinero() {
        return jtDinero;
    }
    
    public void setNombre(String name){
        Name = name;
    }
    /**
     * Creates new form PlayerStatus
     */
    public void setVisiblePanelIA(boolean val) {
        panelIA.setVisible(val);
    }

    public PlayerStatus() {
        visible = true;
        initComponents();
        subirPlayer.setVisible(!visible);
        jtSubir.setText("0");
        jtSubir.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent pce) {
                jSlider1.setValue(Integer.parseInt(jtSubir.getText()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String getJtX(){
        return jtX.getText();
    }
    public String getJtQ(){
        return jtX.getText();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtProbabilidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtDinero = new javax.swing.JTextField();
        accionPlayer = new javax.swing.JPanel();
        jbtnPasar = new javax.swing.JButton();
        jbtnSubir = new javax.swing.JButton();
        jbtnRetirarse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtObligada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtApuesta = new javax.swing.JTextField();
        subirPlayer = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jbApostar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtSubir = new javax.swing.JTextField();
        panelIA = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtQ = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Probabilidad de ganar:");

        jtProbabilidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtProbabilidad.setText("0.0%");
        jtProbabilidad.setEnabled(false);

        jLabel2.setText("Dinero $:");

        jtDinero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtDinero.setText("0");
        jtDinero.setEnabled(false);
        jtDinero.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtDineroPropertyChange(evt);
            }
        });

        accionPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtnPasar.setText("Pasar");

        jbtnSubir.setText("Subir");
        jbtnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubirActionPerformed(evt);
            }
        });

        jbtnRetirarse.setText("Retirarse");

        javax.swing.GroupLayout accionPlayerLayout = new javax.swing.GroupLayout(accionPlayer);
        accionPlayer.setLayout(accionPlayerLayout);
        accionPlayerLayout.setHorizontalGroup(
            accionPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnPasar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnRetirarse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        accionPlayerLayout.setVerticalGroup(
            accionPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accionPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPasar)
                    .addComponent(jbtnSubir)
                    .addComponent(jbtnRetirarse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Obligada $:");

        jtObligada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtObligada.setText("0");
        jtObligada.setEnabled(false);

        jLabel4.setText("Apuesta $:");

        jtApuesta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtApuesta.setText("0");
        jtApuesta.setEnabled(false);

        subirPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMaximum(1000);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setName(""); // NOI18N
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jbApostar.setText("Apostar");
        jbApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApostarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtSubir.setEnabled(false);

        javax.swing.GroupLayout subirPlayerLayout = new javax.swing.GroupLayout(subirPlayer);
        subirPlayer.setLayout(subirPlayerLayout);
        subirPlayerLayout.setHorizontalGroup(
            subirPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subirPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subirPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(subirPlayerLayout.createSequentialGroup()
                        .addComponent(jbApostar)
                        .addGap(67, 67, 67)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jtSubir, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                .addContainerGap())
        );
        subirPlayerLayout.setVerticalGroup(
            subirPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subirPlayerLayout.createSequentialGroup()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subirPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbApostar)
                    .addComponent(jbCancelar)
                    .addComponent(jtSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");

        jtX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtXActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("q");

        jtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIALayout = new javax.swing.GroupLayout(panelIA);
        panelIA.setLayout(panelIALayout);
        panelIALayout.setHorizontalGroup(
            panelIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jtX)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtQ))
                .addContainerGap())
        );
        panelIALayout.setVerticalGroup(
            panelIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIALayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subirPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtObligada, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtDinero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtApuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(accionPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtObligada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jtApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accionPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subirPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setVisibleSubir() {
        accionPlayer.setVisible(!visible);
        subirPlayer.setVisible(visible);
    }
    private void jtXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtXActionPerformed

    private void jtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtQActionPerformed

    private void jbtnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubirActionPerformed
        // TODO add your handling code here:
        visible = true;
        jSlider1.setMinimum(new Integer(jtObligada.getText()));
        jSlider1.setMaximum(Math.min(_parent.j1.getMaximaApuesta(),_parent.j2.getMaximaApuesta()));
        jSlider1.setValue(0);
        setVisibleSubir();
    }//GEN-LAST:event_jbtnSubirActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jtSubir.setText(new Integer(jSlider1.getValue()).toString());
    }//GEN-LAST:event_jSlider1StateChanged

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        visible = false;
        setVisibleSubir();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtDineroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtDineroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDineroPropertyChange

    private void jbApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApostarActionPerformed
        // TODO add your handling code here:
        visible = false;
        setVisibleSubir();
        setApuesta(jSlider1.getValue());
    }//GEN-LAST:event_jbApostarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accionPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton jbApostar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbtnPasar;
    private javax.swing.JButton jbtnRetirarse;
    private javax.swing.JButton jbtnSubir;
    private javax.swing.JTextField jtApuesta;
    private javax.swing.JTextField jtDinero;
    private javax.swing.JTextField jtObligada;
    private javax.swing.JTextField jtProbabilidad;
    private javax.swing.JTextField jtQ;
    private javax.swing.JTextField jtSubir;
    private javax.swing.JTextField jtX;
    private javax.swing.JPanel panelIA;
    private javax.swing.JPanel subirPlayer;
    // End of variables declaration//GEN-END:variables

    public void setBorder(boolean val) {
        if (val) {
            setBorder(javax.swing.BorderFactory.createTitledBorder(null, Name+" (TURNO)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 210, 0)));
        } else {
            setBorder(javax.swing.BorderFactory.createTitledBorder(null, Name, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(230, 0, 0)));
        }
    }

    public void setVisibleButton(boolean val) {
        accionPlayer.setVisible(val);
    }

    public void setEnabledButton(boolean val) {
        accionPlayer.setEnabled(val);
    }

    public int getDinero() {
        return Integer.parseInt(jtDinero.getText());
    }

    public void setDinero(Integer dinero) {
        jtDinero.setText(dinero.toString());
    }

    public int getApuesta() {
        return Integer.parseInt(jtApuesta.getText());
    }

    public void setApuesta(Integer dinero) {
        jtApuesta.setText(dinero.toString());
    }

    public int getObligada() {
        return Integer.parseInt(jtObligada.getText());
    }

    public void setObligada(Integer dinero) {
        jtObligada.setText(dinero.toString());
    }

    public void setProbabilidad(Double prob) {
        String formato = (((int)(prob*10000.0))/100.0)+"";
        jtProbabilidad.setText(formato + "%");
    }

    public double getProbabilidad(){
        String s = jtProbabilidad.getText();
        return Double.parseDouble(s.substring(0, s.length()-1));
    }
    
    public JButton getJbtnPasar() {
        return jbtnPasar;
    }

    public JButton getJbtnRetirarse() {
        return jbtnRetirarse;
    }

    public JButton getJbtnSubir() {
        return jbtnSubir;
    }
}
