/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pokerbot;

import javax.swing.JLabel;

/**
 *
 * @author Julio
 */
public class PlayerGraphics extends javax.swing.JPanel {

    /**
     * Creates new form PlayerGraphics
     */
    public PlayerGraphics() {
        initComponents();
    }

    public JLabel getCardGraphic1() {
        return cardGraphic1;
    }

    public void setCardGraphic1(JLabel cardGraphic1) {
        this.cardGraphic1 = cardGraphic1;
    }

    public JLabel getCardGraphic2() {
        return cardGraphic2;
    }

    public void setCardGraphic2(JLabel cardGraphic2) {
        this.cardGraphic2 = cardGraphic2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new javax.swing.JPanel();
        cardGraphic1 = new javax.swing.JLabel();
        cardGraphic2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(315, 225));
        setMinimumSize(new java.awt.Dimension(315, 225));
        setPreferredSize(new java.awt.Dimension(315, 225));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        card1.setPreferredSize(new java.awt.Dimension(320, 220));
        card1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardGraphic1.setMaximumSize(new java.awt.Dimension(160, 220));
        cardGraphic1.setMinimumSize(new java.awt.Dimension(160, 220));
        cardGraphic1.setPreferredSize(new java.awt.Dimension(160, 220));
        card1.add(cardGraphic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 220));

        cardGraphic2.setMaximumSize(new java.awt.Dimension(160, 220));
        cardGraphic2.setMinimumSize(new java.awt.Dimension(160, 220));
        cardGraphic2.setPreferredSize(new java.awt.Dimension(160, 220));
        card1.add(cardGraphic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 220));

        add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card1;
    private javax.swing.JLabel cardGraphic1;
    private javax.swing.JLabel cardGraphic2;
    // End of variables declaration//GEN-END:variables
}
