/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pokerbot;

import javax.swing.JLabel;

/**
 *
 * @author Julio
 */
public class Table extends javax.swing.JPanel {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
    }

    public JLabel getTable1() {
        return table1;
    }

    public void setTable1(JLabel table1) {
        this.table1 = table1;
    }

    public JLabel getTable2() {
        return table2;
    }

    public void setTable2(JLabel table2) {
        this.table2 = table2;
    }

    public JLabel getTable3() {
        return table3;
    }

    public void setTable3(JLabel table3) {
        this.table3 = table3;
    }

    public JLabel getTable4() {
        return table4;
    }

    public void setTable4(JLabel table4) {
        this.table4 = table4;
    }

    public JLabel getTable5() {
        return table5;
    }

    public void setTable5(JLabel table5) {
        this.table5 = table5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table2 = new javax.swing.JLabel();
        table1 = new javax.swing.JLabel();
        table4 = new javax.swing.JLabel();
        table5 = new javax.swing.JLabel();
        table3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table2.setMaximumSize(new java.awt.Dimension(160, 220));
        table2.setMinimumSize(new java.awt.Dimension(160, 220));
        table2.setPreferredSize(new java.awt.Dimension(160, 220));
        add(table2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 220));

        table1.setMaximumSize(new java.awt.Dimension(160, 220));
        table1.setMinimumSize(new java.awt.Dimension(160, 220));
        table1.setPreferredSize(new java.awt.Dimension(160, 220));
        add(table1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 220));

        table4.setMaximumSize(new java.awt.Dimension(160, 220));
        table4.setMinimumSize(new java.awt.Dimension(160, 220));
        table4.setPreferredSize(new java.awt.Dimension(160, 220));
        add(table4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 160, 220));

        table5.setMaximumSize(new java.awt.Dimension(160, 220));
        table5.setMinimumSize(new java.awt.Dimension(160, 220));
        table5.setPreferredSize(new java.awt.Dimension(160, 220));
        add(table5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 160, 220));

        table3.setMaximumSize(new java.awt.Dimension(160, 220));
        table3.setMinimumSize(new java.awt.Dimension(160, 220));
        table3.setPreferredSize(new java.awt.Dimension(160, 220));
        add(table3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 220));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel table1;
    private javax.swing.JLabel table2;
    private javax.swing.JLabel table3;
    private javax.swing.JLabel table4;
    private javax.swing.JLabel table5;
    // End of variables declaration//GEN-END:variables
}
